name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  workflow_dispatch:
#  schedule:
#    - cron: '42 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build on Linux
    steps:
      - uses: actions/checkout@v2

      - name: Print
        run: |
            hostname


      - name: Deploy webhook
        env:
           DEPLOY_SECRET: ${{ secrets.DEPLOY_SECRET }}
        run: |
            curl --silent --data "secret=${{secrets.DEPLOY_SECRET}}"  http://104.236.40.108/action

#      - name: Deploy SSH
#        env:
#           PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
#        run: |
#          mkdir ~/.ssh/
#          echo $PRIVATE_KEY > ~/.ssh/id_rsa
#          sudo chmod 600 ~/.ssh/id_rsa
#          #ssh-keyscan -H ${{secrets.DEPLOY_SERVER}} > ~/.ssh/known_hosts
#
#          #echo $MYNAME
#          #echo $MYNAME > code.txt
#          #ls -l
#          #cat code.txt
#          ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@104.236.40.108 hostname

